spring.application.name=math-game
# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.boot.autoconfigure=DEBUG
